### PR TITLE
Added zombie noise test and temporary zombie sprite.

### PR DESCRIPTION
**Pull request by brobotato**
Created a temporary zombie sprite to differentiate it from the player. Added a groan noise and sound test for the zombie, which might be annoying. Feel free to remove it in a future commit.

### CODE REVIEW

**Comment by Repertoi-e** [comment]
Looks good.

**Comment by Bravo555** [comment]
In case you don't know how to do this:
1. Use `git reset 01f94f3` to remove the commit, but keep the changes in the filesystem.
2. Use `git add deps/SFML && commit -m "Updated SFML"`.
3. `git add . && git commit -m "Actual changes"`
4. And finally `git push --force` to overwrite history on your origin remote.

**Comment by brobotato** [comment]
Done

**Comment by Bravo555** [comment]
I meant that second commit message should be about actual changes, not literally "Actual Changes" :D
If you want to fix this you can do this easily if this commit is your head (meaning that this is the latest commit), just: `git commit -m "[new message]" --amend`, again push with `--force` and you're done ;p

**Comment by brobotato** [comment]
Done, unfortunately I could not push fast enough to avoid a merge conflict.

**Comment by Bravo555** [comment]
It's because apparently SFML shouldn't be updated that way. Don't worry, it's our fault. Just remove "Updated SFML" commit and you're set. `git rebase --onto commit-id^ commit-id` should do the job. That's for the first conflict. The second one you need to resolve on your own.

**Pull request closed without merging**
